parameters:
#    say_and_do_proof.example.class: SayAndDo\ProofBundle\Example

services:
#    say_and_do_proof.example:
#        class: %say_and_do_proof.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
