SayAndDo\TaskBundle\Entity\Task:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        status:
            type: string
            length: 16
    manyToOne:
        profile:
            targetEntity: SayAndDo\ProfileBundle\Entity\Profile
            inversedBy: tasks
    lifecycleCallbacks: {  }
