parameters:
#    say_and_do_admin.example.class: SayAndDo\AdminBundle\Example

services:
#    say_and_do_admin.example:
#        class: %say_and_do_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
