SayAndDo\ProfileBundle\Entity\Profile:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        position:
            type: string
            length: 255
        political_party:
            type: string
            length: 255
    oneToMany:
        tasks:
            targetEntity: SayAndDo\TaskBundle\Entity\Task
            mappedBy: profile
    lifecycleCallbacks: {  }
