SayAndDo\PromiseBundle\Entity\Promise:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
                type: string
                length: 255
    oneToOne:
        task:
          targetEntity: SayAndDo\TaskBundle\Entity\Task
          inversedBy: promise
    oneToMany:
        proofs:
            targetEntity: SayAndDo\ProofBundle\Entity\Proof
            mappedBy: promise
    lifecycleCallbacks: {  }
