SayAndDo\PromiseBundle\Entity\Promise:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        task:
          targetEntity: SayAndDo\TaskBundle\Entity\Task
          inversedBy: task
    lifecycleCallbacks: {  }
