parameters:
#    say_and_do_promise.example.class: SayAndDo\PromiseBundle\Example

services:
#    say_and_do_promise.example:
#        class: %say_and_do_promise.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
