parameters:
#    say_and_do_profile.example.class: SayAndDo\ProfileBundle\Example

services:
#    say_and_do_profile.example:
#        class: %say_and_do_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    profile.service:
        class: SayAndDo\ProfileBundle\Service\ProfileService