say_and_do_task_homepage:
    path:     /add_task/
    defaults: { _controller: SayAndDoTaskBundle:Default:index }

say_and_do_task_success:
    path:     /success/
    defaults: { _controller: SayAndDoTaskBundle:Default:success }

sad_task.extract:
    path:     /extract/
    defaults: { _controller: SayAndDoTaskBundle:Default:extract }
    methods:   [POST]
