parameters:
     say_and_do_task.service.class: SayAndDo\TaskBundle\Service\TaskService

services:
  sd_task.service:
      class: %say_and_do_task.service.class%
      arguments: [@doctrine.orm.default_entity_manager]