parameters:
#    say_and_do_task.example.class: SayAndDo\TaskBundle\Example

services:
#    say_and_do_task.example:
#        class: %say_and_do_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
